version: "3"
services:
  frontend:
    environment:
      NODE_ENV: development
      CI: "true" # Removes the colors in Jest output
    command: tail -f /dev/null
  backend:
    build:
      args:
        MIX_ENV: test
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/caffe_test
    command: tail -f /dev/null
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: caffe_test
