version: "3"
services:
  frontend:
    build:
      context: ./frontend
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    command: sh -c './wait-for db:5432 -t 60 -- mix db.migrate && mix phx.server'
  db:
    image: postgres:11.6-alpine
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
