version: "3"
services:
  frontend:
    volumes:
      - ./frontend:/code
    ports:
      - 4001:4001
      - 4999:4999
    environment:
      NODE_ENV: development
      HMR_PORT: 4999
    tty: true
  backend:
    # This is forcing mix to recompile everytime
    # volumes:
    #   - ./backend:/code
    ports:
      - 4000:4000
    build:
      args:
        MIX_ENV: dev
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/caffe_dev
      EVENTSTORE_DATABASE_URL: ecto://postgres:postgres@db/caffe_eventstore_dev
    command: sh -c './wait-for db:5432 -t 60 -- mix db.migrate && mix phx.server'
  db:
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: caffe_dev,caffe_eventstore_dev
